[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

[features]
debug = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.6.2"
env_logger = "*"
log = "*"
pixels = "0.13.0"
winit = {version = "0.30.0", features = ["rwh_05"]}
