[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "*"
rusttype = "0.9.3"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["ttf"]
